version: '3.7'
services: 
  snek_site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5005:5000
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
    restart: always
    volumes:
      - ./:/app/
