version: '3.7'
services: 
  snek_site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5005:8000
    depends_on:
      - postgres
    environment:
      DEBUG: "false"
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    volumes:
      - ./:/app/
      - /apps/static/sneknetwork.com/:/app/static/

  postgres:
    image: postgres:latest
    expose:
    - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

volumes:
  postgres_data:
