# Generated by Django 3.0.8 on 2020-07-19 22:23

import api.models.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildConfig',
            fields=[
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Guild')),
                ('admin_role', models.OneToOneField(help_text='The administrator role of a guild.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_in_guild_config', to='api.Role')),
                ('mod_role', models.OneToOneField(help_text='The moderator role of a guild.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_in_guild_config', to='api.Role')),
            ],
            bases=(api.models.utils.ModelReprMixin, models.Model),
        ),
    ]
