# Generated by Django 3.0.8 on 2020-07-22 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200721_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildconfig',
            name='guild',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='api.Guild'),
        ),
    ]
