# Generated by Django 3.0.8 on 2020-07-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200722_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guilds',
            field=models.ManyToManyField(blank=True, to='api.Guild'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='api.Role'),
        ),
    ]
