# Generated by Django 3.0.8 on 2020-07-26 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200726_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime when a guild was created.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime when a role was created.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime when a user was created.'),
            preserve_default=False,
        ),
    ]
