# Generated by Django 3.0.8 on 2020-07-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200726_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildconfig',
            name='command_prefix',
            field=models.CharField(default='!', help_text='The prefix for commands in a guild.', max_length=3),
        ),
    ]
